### ISSUE TITLE
Enhancement - Add support for env and ansible vars in inventory validation

### ISSUE THREAD

**Issue by jpsteinberg** [IBM/zmodstack-solutions#3]
When validating the inventory files with the plugin, ansible and environment variables are not evaluated. This causes the validation to fail. When executing the script skipping the validation, the variables are properly evaluated by ansible and doesn't cause any issue. 
- Add support for the plugin to evaluate the variables for validation

**Comment by acrand06** [comment]
Resolved with PR https://github.com/IBM/zmodstack-solutions/pull/2
